name: Auto Merge staging-frontend to build/staging-frontend

on:
 push:
    branches:
    - staging-frontend


jobs:
  check-commit-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: staging-frontend

    - name: Get Latest Commit Message
      id: latest_commit
      run: |
        latest_commit_message=$(git log -1 --format=%B)
        echo "::set-output name=commit_message::$latest_commit_message"

    - name: Display Latest Commit Message
      run: |
        echo "Latest commit message on staging-frontend:"
        echo "${{ steps.latest_commit.outputs.commit_message }}"

    - name: Merge Changes
      run: |
        git checkout build/staging-frontend
        git pull origin build/staging-frontend
        git merge --no-ff --no-edit staging-frontend
        git push origin build/staging-frontend
